### ISSUE TITLE
SearchResult.results has no items, fails swagger validation

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1475]
```
  SearchResult:
    type: object
    properties:
      es_query:
	description: Elasticsearch query used to produce the results.
        type: object
      results:
        description: Results matching the `es_query`.
        type: array
      total_hits:
        description: The total number of matching results found.
        type: integer
```

items of type array should have an items key describing what sort of items are returned.

https://swagger.io/docs/specification/data-models/data-types/#array

`Unlike JSON Schema, the items keyword is required in arrays.`
